### ISSUE TITLE
Using pangenome variation on my own dataset

### ISSUE THREAD

**Issue by madeleinevlt** [leoisl/pangenome_variations#16]
Hello,

I'm not sure if I should make the issue here or on another fork, I'm a bit lost with all of github repertory for the paper https://doi.org/10.1101/2020.11.12.380378 .
I would like to try to find pan-genome variant on my own assemblies. What I don't really understand is why the use of a mask in mandatory (I tried to remove it in the csv file but it doesn't work). Also, I am new to snakemake, and I really don't know where or how should I look to all the option you can add in the yaml file. Where should I look ?

Thank you

**Comment by leoisl** [comment]
Dear @madeleinevlt ,

sorry for my delay on answering, I was off for some time. All the options to the snakemake pipeline can be found for eg in https://github.com/leoisl/pangenome_variations/blob/master/config.pandora_paper_tag1.yaml . The mask is indeed mandatory, but if you don't want to provide one, just provide an empty bed file.
